[build-system]
name="ogialibs"
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
version = "0.0.1"
authors = [
  { name="Koray Kalmaz", email="koray@kalmaz.com" },
]
readme = "README.md"
requires-python = ">=3.8"
